version: '3.8'
services:
  web:
    container_name: "spotify-clone-web"
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    container_name: "spotify-clone-db"
    image: mysql
    restart: unless-stopped
    env_file:
      - ./.env.docker
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/:ro
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: unless-stopped
    environment:
        PMA_HOST: db
    env_file:
      - .env.docker
    depends_on:
        - db
